### ISSUE TITLE
Charge status not translated in Norwegian

### ISSUE THREAD

**Issue by Amokk123** [WJDDesigns/Ultra-Vehicle-Card#101]
Only one issue.. The card it self, is translated to my language Norwegian. But the car status, Connected, disconected ,charging etc are NOT translated to Norwegian. See picture
![Screenshot 2024-09-15 at 14-27-02 Test – Home Assistant](https://github.com/user-attachments/assets/fd483c9e-beca-4bc6-afdf-9108edfee16c)

PS. I like this card, a lot . Keep up the good work

**Comment by WJDDesigns** [comment]
Fixed in 1.6.1 thanks!

**Comment by Amokk123** [comment]
Not a big issue, but the Charge status is still not translated.. Cache is deleted etc..
