### ISSUE TITLE
PayPal link does not work

### ISSUE THREAD

**Issue by sanchosk** [WJDDesigns/Ultra-Vehicle-Card#12]
Thanks for the awesome extension.
I tried to "donate with PayPal" in the HACS screen, it does not work.
Clicking on the same link on github opens paypal correctly.
Perhaps check that...

**Comment by sanchosk** [comment]
This seems to be firefox protection - maybe open it in new window?
![Screenshot 2024-08-05 113143](https://github.com/user-attachments/assets/dbad874c-c6e7-4087-b786-ebf0cd1344b6)

**Comment by AlexandreLogist** [comment]
--> From HACS

Tested on Chrome 127.0.6533.89 -> OK (Latest version)
Tested on Firefox 123.0 -> Ok
Tested on Firefox 123.0.1 -> Ok
Tested on Firefox 127.0 -> Ok
Tested on Firefox 128.0.3 -> Ok (Latest version)

@sanchosk 
- What browser version are you on ?
- Can you test incognito ?
- Do you use some kind of password manager to fill in paypal credentials (bitwarden) ?

**Comment by AlexandreLogist** [comment]
On 115.13.0esr (64-bit) on Windows it works. I do not directly have the option to test on Debian today.
But it seems that you indicated that it does not open to a new screen? However, the code indicates it should.

```
<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=4JVCZ46FZPUTG" target="_blank" rel="noreferrer noopener">
  <img src="https://raw.githubusercontent.com/stefan-niedermann/paypal-donate-button/master/paypal-donate-button.png" alt="Donate with PayPal">
</a>
```

What version of the plugin are you on ?
[![Open your Home Assistant instance and open a repository inside the Home Assistant Community Store.](https://my.home-assistant.io/badges/hacs_repository.svg)](https://my.home-assistant.io/redirect/hacs_repository/?repository=Ultra-Vehicle-Card&owner=WJDDesigns)

**Comment by sanchosk** [comment]
Yep, on both browsers it tries to open the paypal link inside the frame, not in new window - this, I guess, is the root cause of the problem.

**Comment by AlexandreLogist** [comment]
Can you check for the code behind the button in your HACS?
(Right click, inspect element) ?

**Comment by sanchosk** [comment]
![image](https://github.com/user-attachments/assets/42c4c4c4-a73e-492e-8055-115c7835a070)
No _blank for me :(

**Comment by WJDDesigns** [comment]
Fixed in latest build also replicated from readme and info files. Should all be good now!

**Comment by sanchosk** [comment]
Sorry, but with 1.1.6 the link is not working, I still don't have the target _blank in the a href tag.

**Comment by sanchosk** [comment]
What's more interesting - while I can see the README.md code with the href target _blank, even in the github page itself it does not open in new window.
And I am using different debian with stock firefox and no plugins this time - not even ublox.

**Comment by sanchosk** [comment]
The URL on the github page as displayed by inspect element in FF:
`<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=4JVCZ46FZPUTG" rel="nofollow">
  <img src="https://raw.githubusercontent.com/stefan-niedermann/paypal-donate-button/master/paypal-donate-button.png" alt="Donate with PayPal" style="width: 150px; max-width: 100%;">
</a>`
The URL in code does not have the rel="nofollow", instead it has target="_blank". Is it possible this has something to do with firefox "no track" setting?

**Comment by sanchosk** [comment]
Tested with Chromium now, the result is the same - no target, but rel=nofollow in the link. Is it possible the link is replaced by GitHub when rendering the .md file?
