### ISSUE TITLE
Display of duration entity

### ISSUE THREAD

**Issue by loryanstrant** [WJDDesigns/Ultra-Vehicle-Card#204]
Firstly let me say, this card is AWESOME! Thank you! We just got a new EV so this is perfect for displaying it.

I've just switched to V2 and recreated my config fine, but one of the sensors isn't showing up the same as it did in V1.

![Image](https://github.com/user-attachments/assets/b442f75d-f256-4f9f-90dc-1aebedd3dd78)

This is how the sensor shows up normally (and did in V1):

![Image](https://github.com/user-attachments/assets/409c06a8-065d-4891-9040-eb7ef9c0e4e1)

But this is how it shows up in V2:

![Image](https://github.com/user-attachments/assets/1ab04120-0acb-42c0-8961-7d95ea8e312c)
(obviously the values changed somewhat between screenshots)

**Comment by loryanstrant** [comment]
Actually, similar issue with another entity:

![Image](https://github.com/user-attachments/assets/368919ae-6496-4c29-ad7e-7dd40f52b87a)

This would normally say "Solar" instead of "Pv".
Not sure exactly where it's pulling that display name value from though:

![Image](https://github.com/user-attachments/assets/f59c7a82-e1ec-49b4-9741-1a410fd298a3)

**Comment by WJDDesigns** [comment]
> Actually, similar issue with another entity:
> 
> ![Image](https://github.com/user-attachments/assets/368919ae-6496-4c29-ad7e-7dd40f52b87a)
> 
> This would normally say "Solar" instead of "Pv". Not sure exactly where it's pulling that display name value from though:
> 
> ![Image](https://github.com/user-attachments/assets/f59c7a82-e1ec-49b4-9741-1a410fd298a3)

I am confused the options are off,pv,minipv,now so it would only shows the items in the state area, I do not see Solar as an option. The card will only grab from the state?

**Comment by loryanstrant** [comment]
I don't fully get it, but here is the view of the entity as a more-info popup as well as showing the entity state:

![Image](https://github.com/user-attachments/assets/98aa50ea-f271-4543-a26b-25f045882b1b)

**Comment by loryanstrant** [comment]
In developer tools it shows this unfortunately:

![Image](https://github.com/user-attachments/assets/fff2edad-9bf3-49e9-9f35-53b71a4200f3)

I think it's the formatting of the values, like with the change from the V1 to V2 version of the card with the same entity I use to measure time to full charge - it showing the entity value instead of the formatted version.

**Comment by macr02s** [comment]
First, thanks for a great card! 
But in this version it shows numbers with multiple decimals. Now it shows with charging value with 3 decimals, would like to have one or zero. 
And also another strange thing is, that it shows not correct name that I have in my Zones, but less important :) One of two cars shows correct. 

![Image](https://github.com/user-attachments/assets/db789ea4-9284-4cf0-96c1-c05ef989dd63)

**Comment by loryanstrant** [comment]
Same here. My sensors are set to only show 1 decimal place, but the card is showing all the decimals. It's like it ignores the setting of the sensor and displays the raw value.

**Comment by WJDDesigns** [comment]
Have you all tried the newest beta?

**Comment by loryanstrant** [comment]
That's fixed all of the items, thanks!

**Comment by WJDDesigns** [comment]
Do you have Format Entities on? Also check your display precision of that entity as we abide by that first.

**Comment by loryanstrant** [comment]
Yeah I do. And precision entities is also set:

![Image](https://github.com/user-attachments/assets/76d19835-c3b9-4b06-9d5b-0652cb5a6d6e)

This went away in V2.5-beta2 but has come back in 2.6.
When I flick the options for Format Entities or Show Units, it only seems to affect the first column - not the second one (which was what happened before V2.5-beta2).

**Comment by WJDDesigns** [comment]
Can you right click, inspect the page and see what version it says in console?

**Comment by loryanstrant** [comment]
2.6.1:
![Image](https://github.com/user-attachments/assets/f92552fd-47df-4d9d-9593-78184dcba76a)

**Comment by WJDDesigns** [comment]
> 2.6.1:
> ![Image](https://github.com/user-attachments/assets/f92552fd-47df-4d9d-9593-78184dcba76a)

Try updating to the newest build I put out tonight. Restart/Clear Cache and test it out. It should fix it. Also toggle the format entities on and off.

**Comment by loryanstrant** [comment]
I just pressed submit on that and saw you released 2.6.2 (thank you for your continual efforts), but unfortunately it's still the same problem (and I've confirmed that it's loading 2.6.2):

![Image](https://github.com/user-attachments/assets/66d5a30f-2885-4cbb-8495-0e6916281fb6)

**Comment by WJDDesigns** [comment]
Can you join our Discord so we can chat and figure this out a little quicker?
