### ISSUE TITLE
Automation from Icon Grid not executed

### ISSUE THREAD

**Issue by fuchsbau123** [WJDDesigns/Ultra-Vehicle-Card#47]
Ultra Vehicle Card Version 1.3.3
Home Assistant: 2024.6.4

Hi,
thanks for your great card. I configured an automation to refresh the data from Kia when pressing an icon.
I can run the automation manually without any issue.
When I click to the icon, the automation is not executed.
I cannot find any message in the debug log.
Any idea?

Here the config:
![image](https://github.com/user-attachments/assets/2eeb88d6-01a3-4763-ba67-281aa84c1148)

Here the the yaml code from the config editor:
```
[..]
icon_grid_entities:
   - sensor.ev9_last_updated_at
icon_interactions:
  sensor.ev9_last_updated_at:
    type: automation
    automation: automation.kia_update
[..]
```

**Comment by WJDDesigns** [comment]
Yup, fixed in new version coming soon. Remove "Automation" interaction and replaced with "Trigger" which will trigger the automation you pick in the entity picker.

**Comment by sohlman67** [comment]
I believe that using Automations is not the most optimal thing here. This can cause confustion to users that is used to the names Autonation vs Script in HA.
An Automation in HA is always started by a some trigger, and that trigger is in many (but not all) cases part of the evaluation and actions. Here we just want to execute some actions, hence, we should call a script (instead of an automation), which is only a series of actions.
Suggestions is to actually replace the populated Automations with current available Scripts in HA instead.

**Comment by WJDDesigns** [comment]
What I did was add trigger which will work for Automations (if needed, look I get it why would you want to trigger an automation to happen if it's uhhh automated) scripts, scenes or any entity that is in the entity picker that needs triggered vs toggled.

**Comment by WJDDesigns** [comment]
Fixed in V1.4.0

**Comment by fuchsbau123** [comment]
> What I did was add trigger which will work for Automations (if needed, look I get it why would you want to trigger an automation to happen if it's uhhh automated) scripts, scenes or any entity that is in the entity picker that needs triggered vs toggled.

I installed the latest version 1.4.0. 
I am still see only "automation" and no "trigger" in the "Icon Grid" section under "Interaction".
If I click to the icon the automation selected under "Interaction" is still not executed.
I cannot see any script or scenes in the entity picker...

![image](https://github.com/user-attachments/assets/72e5edc8-58ed-43f9-8102-dd565fa51c22)
