### ISSUE TITLE
Info: common.battery and common.range 

### ISSUE THREAD

**Issue by Amokk123** [WJDDesigns/Ultra-Vehicle-Card#58]
I suddenly got som aditional info: common.battery and common.range below battery and distance(sees picture)
I have cleared cache, but still same issue
![Screenshot_2024-08-21-18-48-19-19_4641ebc0df1485bf6b47ebd018b5ee76](https://github.com/user-attachments/assets/97ea21eb-71fc-422a-9eff-12fff90b4dec)

**Comment by WJDDesigns** [comment]
This should be fixed in V1.5.2 if not please let us know!

**Comment by Titou84240** [comment]
Hi , For me i still have the problem : 

![Image](https://github.com/user-attachments/assets/ad9df77c-0e60-47e4-9818-fdac05289d4a)

On the version 2.5.5, Can someone help please ?
